//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int a_id { get; set; }
        [Required(ErrorMessage ="enter user Name")]
        [Display(Name ="User Name")]
        public string a_name { get; set; }
        [Required(ErrorMessage = "enter user password")]
        [Display(Name = "Password")]

        public string a_password { get; set; }
        public string a_date { get; set; }
    }
}
