//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bloodbankregistration
    {
        public int d_id { get; set; }
        public string d_name { get; set; }
        public string d_gender { get; set; }
        public string d_dateofbirth { get; set; }
        public string d_father { get; set; }
        public string d_bloodgroup { get; set; }
        public string d_contact { get; set; }
        public string d_city { get; set; }
        public string d_meritalstatus { get; set; }
    }
}
