//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctorDetail
    {
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string age { get; set; }
        public string gender { get; set; }
        public string fathername { get; set; }
        public string qualification { get; set; }
        public string city { get; set; }
        public string contact { get; set; }
    }
}
