//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class doctorLogin
    {
        public int id { get; set; }
        [Display(Name = "UserName")]
        [Required (ErrorMessage ="enter user name")]
        public string name { get; set; }
        [Display(Name ="Password")]
        [Required(ErrorMessage = "enter user password")]
        [DataType (DataType.Password)]
        public string password { get; set; }
    }
}
