//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<bloodbankregistration> bloodbankregistrations { get; set; }
        public virtual DbSet<bloodgroup> bloodgroups { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<receaptioninquery> receaptioninqueries { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<doctorDetail> doctorDetails { get; set; }
        public virtual DbSet<doctorLogin> doctorLogins { get; set; }
    }
}
