//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class receaptioninquery
    {
        public int r_id { get; set; }
        [Required(ErrorMessage ="please enter name ")]
        [Display(Name ="Name")]
        public string r_name { get; set; }
        [Required(ErrorMessage = "please enter Gender ")]
        [Display(Name = "Gender")]
        public string r_gender { get; set; }
        [Required(ErrorMessage = "please your Query ")]
        [Display(Name = "Query")]
        public string r_query { get; set; }
    }
}
