//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class registration
    {
        public int r_id { get; set; }
        [Required (ErrorMessage ="enter your name")]
        [Display(Name ="user name")]
        public string r_name { get; set; }
        [Required(ErrorMessage = "enter your name")]
        [Display(Name = "Gender")]
        public string r_Gender { get; set; }
        [Required(ErrorMessage = "enter your name")]
        [Display(Name = "AppoinmentDate")]
        [DataType(DataType.Date)]
        public string r_date { get; set; }
        [Required(ErrorMessage = "enter your name")]
        [Display(Name = "City")]
        public string r_city { get; set; }
        [Required(ErrorMessage = "enter your mobile number")]
        [Display(Name = "Mobile")]
        [RegularExpression(@"^(0|91)?[6789]\d{9}$", ErrorMessage = "Invalid Indian mobile number.")]
        public string r_contact { get; set; }
    }
}
